name: GitHub Pages
on:
  schedule:
    - cron: '0 0,12 * * 1'
  workflow_dispatch:
jobs:
  gh-pages:
    name: GitHub Pages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        books: ['jungno', 'yeokhae']
    steps:
      - uses: actions/checkout@v2

      - run: chmod +x ${{ matrix.build-dir }}-dl.sh
      - run: ./${{ matrix.build-dir }}-dl.sh

      - run: pip install -r ${{ matrix.build-dir }}-requirements.txt
      - run: sed -E --in-place 's/; dragon.+//g' ${{ matrix.build-dir }}.sh
      - run: chmod +x ${{ matrix.build-dir }}.sh
      - run: ./${{ matrix.build-dir }}.sh

      - run: git checkout --orphan gh-pages || git checkout gh-pages
      - run: git rm -rf .
      - run: cp /tmp/${{ matrix.build-dir }}.* .
      - run: git add ${{ matrix.build-dir }}.*
      - run: git config user.email '-'
      - run: git config user.name 'GitHub Actions'
      - run: git commit -m 'Update'
      - run: git push --set-upstream origin gh-pages
