name: GitHub Pages
on:
  schedule:
    - cron: '0 0,12 * * 1'
  workflow_dispatch:
jobs:
  gh-pages:
    name: GitHub Pages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        book: ['jungno', 'yeokhae']
    steps:
      - uses: actions/checkout@v2

      - name: chmod
        run: |
          chmod +x *.sh *.py

      - name: Download SDL
        run: |
          ./download-sdl.sh

      - name: Download book
        run: |
          ./${{ matrix.book }}-dl.sh

      - name: Generate tables
        run: |
          pip install -r ${{ matrix.book }}-requirements.txt
          sed -E --in-place 's/; dragon.+//g' ${{ matrix.book }}.sh
          ./${{ matrix.book }}.sh

      - name: Push
        run: |
          git checkout --orphan gh-pages || git checkout gh-pages
          git rm -rf .
          cp /tmp/${{ matrix.book }}.* .
          git add ${{ matrix.book }}.*
          git config user.email '-'
          git config user.name 'GitHub Actions'
          git commit -m 'Update'
          git push --set-upstream origin gh-pages
