name: GitHub Pages
on:
  schedule:
    - cron: '0 0,12 * * 1'
  workflow_dispatch:
jobs:
  gh-pages:
    name: GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: wget "https://raw.githubusercontent.com/${GITHUB_ACTOR}/sdl/main/sdl.py"
      - run: wget "https://raw.githubusercontent.com/${GITHUB_ACTOR}/sdl/main/sdl-requirements.txt"
      - run: pip install -r sdl-requirements.txt
      - run: chmod +x sdl.py
      - run: ./sdl.py "ko:重刊老乞大諺解 001.pdf" -o /tmp/sdl/jungno-a &
      - run: ./sdl.py "ko:重刊老乞大諺解 002.pdf" -o /tmp/sdl/jungno-b &

      - run: pip install -r jungno-requirements.txt
      - run: sed -E --in-place 's/; dragon.+//g' jungno.sh
      - run: chmod +x jungno.sh
      - run: ./jungno.sh

      - run: git checkout --orphan gh-pages || git checkout gh-pages
      - run: ls
      - run: git rm -rf .
      - run: ls
      - run: cp /tmp/jungno.* .
      - run: git add jungno.*
      - run: git config user.email '-'
      - run: git config user.name 'GitHub Actions'
      - run: git commit -m 'Update'
      - run: git push --set-upstream origin gh-pages
