name: GitHub Pages
on:
  schedule:
    - cron: '0 0,12 * * 1'
  workflow_dispatch:
jobs:
  gh-pages:
    name: GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          wget "https://raw.githubusercontent.com/${GITHUB_ACTOR}/sdl/main/sdl.py"
          wget "https://raw.githubusercontent.com/${GITHUB_ACTOR}/sdl/main/sdl-requirements.txt"
          pip install -r sdl-requirements.txt
          chmod +x sdl.py
          ./sdl.py "ko:重刊老乞大諺解 001.pdf" -o /tmp/sdl/jungno-a &
          ./sdl.py "ko:重刊老乞大諺解 002.pdf" -o /tmp/sdl/jungno-b &

          pip install -r jungno-requirements.txt
          sed -E --in-place 's/; dragon.+//g' jungno.sh
          chmod +x jungno.sh
          ./jungno.sh

          git checkout --orphan gh-pages || git checkout gh-pages
          ls
          rm * -rv
          ls
          cp /tmp/jungno.* .
          git add jungno.*
          git config user.email '-'
          git config user.name 'GitHub Actions'
          git commit -m 'Update'
          git push --set-upstream origin gh-pages
